site_name: IMP Documentation
site_url: https://imptechnology.github.io/

nav:
  - Home: index.md
  - How to use: howto.md
  - ZÃ¡pisnice: zapisnice.md
theme:
  name: material
  font: false
  palette:
    primary: purple
    accent: pink
    scheme: slate
